apiVersion: v1
kind: Deployment
metadata: 
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
    replicas: 1
    selector: 
      matchLabels:
        app: mongodb
    templetes:
        metadata:
          labels:
            app: mongodb
        spec: 
          containers:
          - name: mongodb
            image: mongo
            ports:
            - containerPort: 2701
            env:
            - name: MONGO_INIT_ROOT_USERNAME
              valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-user
            - name: MONGO_INIT_ROOT_PASSWORD
              valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
